server:
  name: "cities-svc"

rest:
  port: ":8003"
  timeouts:
    read: 15 #seconds
    read_header: 15 #seconds
    write: 15 #seconds
    idle: 60 #seconds

log:
  level: "debug"
  format: "text"


database:
  sql:
    url: "postgresql://postgres:postgres@localhost:7777/postgres?sslmode=disable"

jwt:
  user:
    access_token:
      secret_key: "supersecretkey"
      token_lifetime: 900
    refresh_token:
      secret_key: "refreshsuperkey"
      encryption_key: "f6tD7wVYNvXMm4MwqivfpB9Gf+HYz8a3"  # Key for decrypting Refresh Token in the database
      token_lifetime: 604800
  service:
    secret_key: "servicesuperkey"
  gov-invites:
    secret_key: "invitesuperkey"

kafka:
  brokers:
    - "re-news-kafka:XXXX"

swagger:
  enabled: true
  url: "/swagger"
  port: "XXXX"
