/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateCityAdminDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCityAdminDataAttributes{}

// UpdateCityAdminDataAttributes struct for UpdateCityAdminDataAttributes
type UpdateCityAdminDataAttributes struct {
	// optional role
	Role *string `json:"role,omitempty"`
	// optional label for the user in this city
	Label *string `json:"label,omitempty"`
	// optional position for the user in this city
	Position *string `json:"position,omitempty"`
}

// NewUpdateCityAdminDataAttributes instantiates a new UpdateCityAdminDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCityAdminDataAttributes() *UpdateCityAdminDataAttributes {
	this := UpdateCityAdminDataAttributes{}
	return &this
}

// NewUpdateCityAdminDataAttributesWithDefaults instantiates a new UpdateCityAdminDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCityAdminDataAttributesWithDefaults() *UpdateCityAdminDataAttributes {
	this := UpdateCityAdminDataAttributes{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UpdateCityAdminDataAttributes) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCityAdminDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UpdateCityAdminDataAttributes) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UpdateCityAdminDataAttributes) SetRole(v string) {
	o.Role = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UpdateCityAdminDataAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCityAdminDataAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateCityAdminDataAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UpdateCityAdminDataAttributes) SetLabel(v string) {
	o.Label = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *UpdateCityAdminDataAttributes) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCityAdminDataAttributes) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *UpdateCityAdminDataAttributes) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *UpdateCityAdminDataAttributes) SetPosition(v string) {
	o.Position = &v
}

func (o UpdateCityAdminDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCityAdminDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableUpdateCityAdminDataAttributes struct {
	value *UpdateCityAdminDataAttributes
	isSet bool
}

func (v NullableUpdateCityAdminDataAttributes) Get() *UpdateCityAdminDataAttributes {
	return v.value
}

func (v *NullableUpdateCityAdminDataAttributes) Set(val *UpdateCityAdminDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCityAdminDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCityAdminDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCityAdminDataAttributes(val *UpdateCityAdminDataAttributes) *NullableUpdateCityAdminDataAttributes {
	return &NullableUpdateCityAdminDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateCityAdminDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCityAdminDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


