/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCityAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCityAdmin{}

// UpdateCityAdmin struct for UpdateCityAdmin
type UpdateCityAdmin struct {
	Data UpdateCityAdminData `json:"data"`
}

type _UpdateCityAdmin UpdateCityAdmin

// NewUpdateCityAdmin instantiates a new UpdateCityAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCityAdmin(data UpdateCityAdminData) *UpdateCityAdmin {
	this := UpdateCityAdmin{}
	this.Data = data
	return &this
}

// NewUpdateCityAdminWithDefaults instantiates a new UpdateCityAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCityAdminWithDefaults() *UpdateCityAdmin {
	this := UpdateCityAdmin{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateCityAdmin) GetData() UpdateCityAdminData {
	if o == nil {
		var ret UpdateCityAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateCityAdmin) GetDataOk() (*UpdateCityAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateCityAdmin) SetData(v UpdateCityAdminData) {
	o.Data = v
}

func (o UpdateCityAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCityAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateCityAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCityAdmin := _UpdateCityAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCityAdmin)

	if err != nil {
		return err
	}

	*o = UpdateCityAdmin(varUpdateCityAdmin)

	return err
}

type NullableUpdateCityAdmin struct {
	value *UpdateCityAdmin
	isSet bool
}

func (v NullableUpdateCityAdmin) Get() *UpdateCityAdmin {
	return v.value
}

func (v *NullableUpdateCityAdmin) Set(val *UpdateCityAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCityAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCityAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCityAdmin(val *UpdateCityAdmin) *NullableUpdateCityAdmin {
	return &NullableUpdateCityAdmin{value: val, isSet: true}
}

func (v NullableUpdateCityAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCityAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


