/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AcceptInviteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AcceptInviteDataAttributes{}

// AcceptInviteDataAttributes struct for AcceptInviteDataAttributes
type AcceptInviteDataAttributes struct {
	// The answer to the invite, either 'accept' or 'decline'
	Answer string `json:"answer"`
}

type _AcceptInviteDataAttributes AcceptInviteDataAttributes

// NewAcceptInviteDataAttributes instantiates a new AcceptInviteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcceptInviteDataAttributes(answer string) *AcceptInviteDataAttributes {
	this := AcceptInviteDataAttributes{}
	this.Answer = answer
	return &this
}

// NewAcceptInviteDataAttributesWithDefaults instantiates a new AcceptInviteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcceptInviteDataAttributesWithDefaults() *AcceptInviteDataAttributes {
	this := AcceptInviteDataAttributes{}
	return &this
}

// GetAnswer returns the Answer field value
func (o *AcceptInviteDataAttributes) GetAnswer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Answer
}

// GetAnswerOk returns a tuple with the Answer field value
// and a boolean to check if the value has been set.
func (o *AcceptInviteDataAttributes) GetAnswerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Answer, true
}

// SetAnswer sets field value
func (o *AcceptInviteDataAttributes) SetAnswer(v string) {
	o.Answer = v
}

func (o AcceptInviteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AcceptInviteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answer"] = o.Answer
	return toSerialize, nil
}

func (o *AcceptInviteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAcceptInviteDataAttributes := _AcceptInviteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAcceptInviteDataAttributes)

	if err != nil {
		return err
	}

	*o = AcceptInviteDataAttributes(varAcceptInviteDataAttributes)

	return err
}

type NullableAcceptInviteDataAttributes struct {
	value *AcceptInviteDataAttributes
	isSet bool
}

func (v NullableAcceptInviteDataAttributes) Get() *AcceptInviteDataAttributes {
	return v.value
}

func (v *NullableAcceptInviteDataAttributes) Set(val *AcceptInviteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAcceptInviteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAcceptInviteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcceptInviteDataAttributes(val *AcceptInviteDataAttributes) *NullableAcceptInviteDataAttributes {
	return &NullableAcceptInviteDataAttributes{value: val, isSet: true}
}

func (v NullableAcceptInviteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcceptInviteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


