/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GovsCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GovsCollection{}

// GovsCollection struct for GovsCollection
type GovsCollection struct {
	Data []GovData `json:"data"`
	Links PaginationData `json:"links"`
}

type _GovsCollection GovsCollection

// NewGovsCollection instantiates a new GovsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGovsCollection(data []GovData, links PaginationData) *GovsCollection {
	this := GovsCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewGovsCollectionWithDefaults instantiates a new GovsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGovsCollectionWithDefaults() *GovsCollection {
	this := GovsCollection{}
	return &this
}

// GetData returns the Data field value
func (o *GovsCollection) GetData() []GovData {
	if o == nil {
		var ret []GovData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GovsCollection) GetDataOk() ([]GovData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GovsCollection) SetData(v []GovData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *GovsCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GovsCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GovsCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o GovsCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GovsCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *GovsCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGovsCollection := _GovsCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGovsCollection)

	if err != nil {
		return err
	}

	*o = GovsCollection(varGovsCollection)

	return err
}

type NullableGovsCollection struct {
	value *GovsCollection
	isSet bool
}

func (v NullableGovsCollection) Get() *GovsCollection {
	return v.value
}

func (v *NullableGovsCollection) Set(val *GovsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableGovsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableGovsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGovsCollection(val *GovsCollection) *NullableGovsCollection {
	return &NullableGovsCollection{value: val, isSet: true}
}

func (v NullableGovsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGovsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


