/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOwnActiveGov type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnActiveGov{}

// UpdateOwnActiveGov struct for UpdateOwnActiveGov
type UpdateOwnActiveGov struct {
	Data UpdateOwnActiveGovData `json:"data"`
}

type _UpdateOwnActiveGov UpdateOwnActiveGov

// NewUpdateOwnActiveGov instantiates a new UpdateOwnActiveGov object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnActiveGov(data UpdateOwnActiveGovData) *UpdateOwnActiveGov {
	this := UpdateOwnActiveGov{}
	this.Data = data
	return &this
}

// NewUpdateOwnActiveGovWithDefaults instantiates a new UpdateOwnActiveGov object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnActiveGovWithDefaults() *UpdateOwnActiveGov {
	this := UpdateOwnActiveGov{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateOwnActiveGov) GetData() UpdateOwnActiveGovData {
	if o == nil {
		var ret UpdateOwnActiveGovData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnActiveGov) GetDataOk() (*UpdateOwnActiveGovData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateOwnActiveGov) SetData(v UpdateOwnActiveGovData) {
	o.Data = v
}

func (o UpdateOwnActiveGov) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnActiveGov) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateOwnActiveGov) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOwnActiveGov := _UpdateOwnActiveGov{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOwnActiveGov)

	if err != nil {
		return err
	}

	*o = UpdateOwnActiveGov(varUpdateOwnActiveGov)

	return err
}

type NullableUpdateOwnActiveGov struct {
	value *UpdateOwnActiveGov
	isSet bool
}

func (v NullableUpdateOwnActiveGov) Get() *UpdateOwnActiveGov {
	return v.value
}

func (v *NullableUpdateOwnActiveGov) Set(val *UpdateOwnActiveGov) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnActiveGov) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnActiveGov) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnActiveGov(val *UpdateOwnActiveGov) *NullableUpdateOwnActiveGov {
	return &NullableUpdateOwnActiveGov{value: val, isSet: true}
}

func (v NullableUpdateOwnActiveGov) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnActiveGov) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


