/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateOwnAdminData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnAdminData{}

// UpdateOwnAdminData struct for UpdateOwnAdminData
type UpdateOwnAdminData struct {
	// user id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdateOwnAdminDataAttributes `json:"attributes"`
}

type _UpdateOwnAdminData UpdateOwnAdminData

// NewUpdateOwnAdminData instantiates a new UpdateOwnAdminData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnAdminData(id uuid.UUID, type_ string, attributes UpdateOwnAdminDataAttributes) *UpdateOwnAdminData {
	this := UpdateOwnAdminData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateOwnAdminDataWithDefaults instantiates a new UpdateOwnAdminData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnAdminDataWithDefaults() *UpdateOwnAdminData {
	this := UpdateOwnAdminData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateOwnAdminData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnAdminData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateOwnAdminData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateOwnAdminData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnAdminData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateOwnAdminData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateOwnAdminData) GetAttributes() UpdateOwnAdminDataAttributes {
	if o == nil {
		var ret UpdateOwnAdminDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnAdminData) GetAttributesOk() (*UpdateOwnAdminDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateOwnAdminData) SetAttributes(v UpdateOwnAdminDataAttributes) {
	o.Attributes = v
}

func (o UpdateOwnAdminData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnAdminData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateOwnAdminData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOwnAdminData := _UpdateOwnAdminData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOwnAdminData)

	if err != nil {
		return err
	}

	*o = UpdateOwnAdminData(varUpdateOwnAdminData)

	return err
}

type NullableUpdateOwnAdminData struct {
	value *UpdateOwnAdminData
	isSet bool
}

func (v NullableUpdateOwnAdminData) Get() *UpdateOwnAdminData {
	return v.value
}

func (v *NullableUpdateOwnAdminData) Set(val *UpdateOwnAdminData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnAdminData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnAdminData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnAdminData(val *UpdateOwnAdminData) *NullableUpdateOwnAdminData {
	return &NullableUpdateOwnAdminData{value: val, isSet: true}
}

func (v NullableUpdateOwnAdminData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnAdminData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


