/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CityData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CityData{}

// CityData struct for CityData
type CityData struct {
	// city id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes CityAttributes `json:"attributes"`
}

type _CityData CityData

// NewCityData instantiates a new CityData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCityData(id uuid.UUID, type_ string, attributes CityAttributes) *CityData {
	this := CityData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCityDataWithDefaults instantiates a new CityData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCityDataWithDefaults() *CityData {
	this := CityData{}
	return &this
}

// GetId returns the Id field value
func (o *CityData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CityData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CityData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CityData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CityData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CityData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CityData) GetAttributes() CityAttributes {
	if o == nil {
		var ret CityAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CityData) GetAttributesOk() (*CityAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CityData) SetAttributes(v CityAttributes) {
	o.Attributes = v
}

func (o CityData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CityData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CityData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCityData := _CityData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCityData)

	if err != nil {
		return err
	}

	*o = CityData(varCityData)

	return err
}

type NullableCityData struct {
	value *CityData
	isSet bool
}

func (v NullableCityData) Get() *CityData {
	return v.value
}

func (v *NullableCityData) Set(val *CityData) {
	v.value = val
	v.isSet = true
}

func (v NullableCityData) IsSet() bool {
	return v.isSet
}

func (v *NullableCityData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCityData(val *CityData) *NullableCityData {
	return &NullableCityData{value: val, isSet: true}
}

func (v NullableCityData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCityData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


