/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CityAdminsCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CityAdminsCollection{}

// CityAdminsCollection struct for CityAdminsCollection
type CityAdminsCollection struct {
	Data []CityAdminData `json:"data"`
	Links PaginationData `json:"links"`
}

type _CityAdminsCollection CityAdminsCollection

// NewCityAdminsCollection instantiates a new CityAdminsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCityAdminsCollection(data []CityAdminData, links PaginationData) *CityAdminsCollection {
	this := CityAdminsCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewCityAdminsCollectionWithDefaults instantiates a new CityAdminsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCityAdminsCollectionWithDefaults() *CityAdminsCollection {
	this := CityAdminsCollection{}
	return &this
}

// GetData returns the Data field value
func (o *CityAdminsCollection) GetData() []CityAdminData {
	if o == nil {
		var ret []CityAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CityAdminsCollection) GetDataOk() ([]CityAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CityAdminsCollection) SetData(v []CityAdminData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *CityAdminsCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *CityAdminsCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *CityAdminsCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o CityAdminsCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CityAdminsCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *CityAdminsCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCityAdminsCollection := _CityAdminsCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCityAdminsCollection)

	if err != nil {
		return err
	}

	*o = CityAdminsCollection(varCityAdminsCollection)

	return err
}

type NullableCityAdminsCollection struct {
	value *CityAdminsCollection
	isSet bool
}

func (v NullableCityAdminsCollection) Get() *CityAdminsCollection {
	return v.value
}

func (v *NullableCityAdminsCollection) Set(val *CityAdminsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableCityAdminsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableCityAdminsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCityAdminsCollection(val *CityAdminsCollection) *NullableCityAdminsCollection {
	return &NullableCityAdminsCollection{value: val, isSet: true}
}

func (v NullableCityAdminsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCityAdminsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


