/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateCityAdminData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCityAdminData{}

// UpdateCityAdminData struct for UpdateCityAdminData
type UpdateCityAdminData struct {
	// user id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdateCityAdminDataAttributes `json:"attributes"`
}

type _UpdateCityAdminData UpdateCityAdminData

// NewUpdateCityAdminData instantiates a new UpdateCityAdminData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCityAdminData(id uuid.UUID, type_ string, attributes UpdateCityAdminDataAttributes) *UpdateCityAdminData {
	this := UpdateCityAdminData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateCityAdminDataWithDefaults instantiates a new UpdateCityAdminData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCityAdminDataWithDefaults() *UpdateCityAdminData {
	this := UpdateCityAdminData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateCityAdminData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateCityAdminData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateCityAdminData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateCityAdminData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateCityAdminData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateCityAdminData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateCityAdminData) GetAttributes() UpdateCityAdminDataAttributes {
	if o == nil {
		var ret UpdateCityAdminDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateCityAdminData) GetAttributesOk() (*UpdateCityAdminDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateCityAdminData) SetAttributes(v UpdateCityAdminDataAttributes) {
	o.Attributes = v
}

func (o UpdateCityAdminData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCityAdminData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateCityAdminData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCityAdminData := _UpdateCityAdminData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCityAdminData)

	if err != nil {
		return err
	}

	*o = UpdateCityAdminData(varUpdateCityAdminData)

	return err
}

type NullableUpdateCityAdminData struct {
	value *UpdateCityAdminData
	isSet bool
}

func (v NullableUpdateCityAdminData) Get() *UpdateCityAdminData {
	return v.value
}

func (v *NullableUpdateCityAdminData) Set(val *UpdateCityAdminData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCityAdminData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCityAdminData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCityAdminData(val *UpdateCityAdminData) *NullableUpdateCityAdminData {
	return &NullableUpdateCityAdminData{value: val, isSet: true}
}

func (v NullableUpdateCityAdminData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCityAdminData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


