/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AcceptInvite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AcceptInvite{}

// AcceptInvite struct for AcceptInvite
type AcceptInvite struct {
	Data AcceptInviteData `json:"data"`
}

type _AcceptInvite AcceptInvite

// NewAcceptInvite instantiates a new AcceptInvite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcceptInvite(data AcceptInviteData) *AcceptInvite {
	this := AcceptInvite{}
	this.Data = data
	return &this
}

// NewAcceptInviteWithDefaults instantiates a new AcceptInvite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcceptInviteWithDefaults() *AcceptInvite {
	this := AcceptInvite{}
	return &this
}

// GetData returns the Data field value
func (o *AcceptInvite) GetData() AcceptInviteData {
	if o == nil {
		var ret AcceptInviteData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AcceptInvite) GetDataOk() (*AcceptInviteData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AcceptInvite) SetData(v AcceptInviteData) {
	o.Data = v
}

func (o AcceptInvite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AcceptInvite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AcceptInvite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAcceptInvite := _AcceptInvite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAcceptInvite)

	if err != nil {
		return err
	}

	*o = AcceptInvite(varAcceptInvite)

	return err
}

type NullableAcceptInvite struct {
	value *AcceptInvite
	isSet bool
}

func (v NullableAcceptInvite) Get() *AcceptInvite {
	return v.value
}

func (v *NullableAcceptInvite) Set(val *AcceptInvite) {
	v.value = val
	v.isSet = true
}

func (v NullableAcceptInvite) IsSet() bool {
	return v.isSet
}

func (v *NullableAcceptInvite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcceptInvite(val *AcceptInvite) *NullableAcceptInvite {
	return &NullableAcceptInvite{value: val, isSet: true}
}

func (v NullableAcceptInvite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcceptInvite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


