/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCityStatusDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCityStatusDataAttributes{}

// UpdateCityStatusDataAttributes struct for UpdateCityStatusDataAttributes
type UpdateCityStatusDataAttributes struct {
	// new city status
	Status string `json:"status"`
}

type _UpdateCityStatusDataAttributes UpdateCityStatusDataAttributes

// NewUpdateCityStatusDataAttributes instantiates a new UpdateCityStatusDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCityStatusDataAttributes(status string) *UpdateCityStatusDataAttributes {
	this := UpdateCityStatusDataAttributes{}
	this.Status = status
	return &this
}

// NewUpdateCityStatusDataAttributesWithDefaults instantiates a new UpdateCityStatusDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCityStatusDataAttributesWithDefaults() *UpdateCityStatusDataAttributes {
	this := UpdateCityStatusDataAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateCityStatusDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateCityStatusDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateCityStatusDataAttributes) SetStatus(v string) {
	o.Status = v
}

func (o UpdateCityStatusDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCityStatusDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateCityStatusDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCityStatusDataAttributes := _UpdateCityStatusDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCityStatusDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateCityStatusDataAttributes(varUpdateCityStatusDataAttributes)

	return err
}

type NullableUpdateCityStatusDataAttributes struct {
	value *UpdateCityStatusDataAttributes
	isSet bool
}

func (v NullableUpdateCityStatusDataAttributes) Get() *UpdateCityStatusDataAttributes {
	return v.value
}

func (v *NullableUpdateCityStatusDataAttributes) Set(val *UpdateCityStatusDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCityStatusDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCityStatusDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCityStatusDataAttributes(val *UpdateCityStatusDataAttributes) *NullableUpdateCityStatusDataAttributes {
	return &NullableUpdateCityStatusDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateCityStatusDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCityStatusDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


