/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateGovDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGovDataAttributes{}

// UpdateGovDataAttributes struct for UpdateGovDataAttributes
type UpdateGovDataAttributes struct {
	// is the user active in this city
	Active *bool `json:"active,omitempty"`
	// optional label for the user in this city
	Label *string `json:"label,omitempty"`
}

// NewUpdateGovDataAttributes instantiates a new UpdateGovDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGovDataAttributes() *UpdateGovDataAttributes {
	this := UpdateGovDataAttributes{}
	return &this
}

// NewUpdateGovDataAttributesWithDefaults instantiates a new UpdateGovDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGovDataAttributesWithDefaults() *UpdateGovDataAttributes {
	this := UpdateGovDataAttributes{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *UpdateGovDataAttributes) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGovDataAttributes) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *UpdateGovDataAttributes) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *UpdateGovDataAttributes) SetActive(v bool) {
	o.Active = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UpdateGovDataAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGovDataAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateGovDataAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UpdateGovDataAttributes) SetLabel(v string) {
	o.Label = &v
}

func (o UpdateGovDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGovDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableUpdateGovDataAttributes struct {
	value *UpdateGovDataAttributes
	isSet bool
}

func (v NullableUpdateGovDataAttributes) Get() *UpdateGovDataAttributes {
	return v.value
}

func (v *NullableUpdateGovDataAttributes) Set(val *UpdateGovDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGovDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGovDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGovDataAttributes(val *UpdateGovDataAttributes) *NullableUpdateGovDataAttributes {
	return &NullableUpdateGovDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateGovDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGovDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


