/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CitiesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CitiesCollection{}

// CitiesCollection struct for CitiesCollection
type CitiesCollection struct {
	Data []CityData `json:"data"`
	Links PaginationData `json:"links"`
}

type _CitiesCollection CitiesCollection

// NewCitiesCollection instantiates a new CitiesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCitiesCollection(data []CityData, links PaginationData) *CitiesCollection {
	this := CitiesCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewCitiesCollectionWithDefaults instantiates a new CitiesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCitiesCollectionWithDefaults() *CitiesCollection {
	this := CitiesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *CitiesCollection) GetData() []CityData {
	if o == nil {
		var ret []CityData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CitiesCollection) GetDataOk() ([]CityData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CitiesCollection) SetData(v []CityData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *CitiesCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *CitiesCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *CitiesCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o CitiesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CitiesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *CitiesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCitiesCollection := _CitiesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCitiesCollection)

	if err != nil {
		return err
	}

	*o = CitiesCollection(varCitiesCollection)

	return err
}

type NullableCitiesCollection struct {
	value *CitiesCollection
	isSet bool
}

func (v NullableCitiesCollection) Get() *CitiesCollection {
	return v.value
}

func (v *NullableCitiesCollection) Set(val *CitiesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableCitiesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableCitiesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCitiesCollection(val *CitiesCollection) *NullableCitiesCollection {
	return &NullableCitiesCollection{value: val, isSet: true}
}

func (v NullableCitiesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCitiesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


