/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCityStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCityStatus{}

// UpdateCityStatus struct for UpdateCityStatus
type UpdateCityStatus struct {
	Data UpdateCityStatusData `json:"data"`
}

type _UpdateCityStatus UpdateCityStatus

// NewUpdateCityStatus instantiates a new UpdateCityStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCityStatus(data UpdateCityStatusData) *UpdateCityStatus {
	this := UpdateCityStatus{}
	this.Data = data
	return &this
}

// NewUpdateCityStatusWithDefaults instantiates a new UpdateCityStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCityStatusWithDefaults() *UpdateCityStatus {
	this := UpdateCityStatus{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateCityStatus) GetData() UpdateCityStatusData {
	if o == nil {
		var ret UpdateCityStatusData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateCityStatus) GetDataOk() (*UpdateCityStatusData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateCityStatus) SetData(v UpdateCityStatusData) {
	o.Data = v
}

func (o UpdateCityStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCityStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateCityStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCityStatus := _UpdateCityStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCityStatus)

	if err != nil {
		return err
	}

	*o = UpdateCityStatus(varUpdateCityStatus)

	return err
}

type NullableUpdateCityStatus struct {
	value *UpdateCityStatus
	isSet bool
}

func (v NullableUpdateCityStatus) Get() *UpdateCityStatus {
	return v.value
}

func (v *NullableUpdateCityStatus) Set(val *UpdateCityStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCityStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCityStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCityStatus(val *UpdateCityStatus) *NullableUpdateCityStatus {
	return &NullableUpdateCityStatus{value: val, isSet: true}
}

func (v NullableUpdateCityStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCityStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


