/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
	"bytes"
	"fmt"
)

// checks if the GovAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GovAttributes{}

// GovAttributes struct for GovAttributes
type GovAttributes struct {
	// city id
	CityId uuid.UUID `json:"city_id"`
	// role of the user in this city
	Role string `json:"role"`
	// optional label for the user in this city
	Label *string `json:"label,omitempty"`
	// record creation date
	CreatedAt time.Time `json:"created_at"`
	// last update date
	UpdatedAt time.Time `json:"updated_at"`
}

type _GovAttributes GovAttributes

// NewGovAttributes instantiates a new GovAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGovAttributes(cityId uuid.UUID, role string, createdAt time.Time, updatedAt time.Time) *GovAttributes {
	this := GovAttributes{}
	this.CityId = cityId
	this.Role = role
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGovAttributesWithDefaults instantiates a new GovAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGovAttributesWithDefaults() *GovAttributes {
	this := GovAttributes{}
	return &this
}

// GetCityId returns the CityId field value
func (o *GovAttributes) GetCityId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.CityId
}

// GetCityIdOk returns a tuple with the CityId field value
// and a boolean to check if the value has been set.
func (o *GovAttributes) GetCityIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CityId, true
}

// SetCityId sets field value
func (o *GovAttributes) SetCityId(v uuid.UUID) {
	o.CityId = v
}

// GetRole returns the Role field value
func (o *GovAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GovAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GovAttributes) SetRole(v string) {
	o.Role = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *GovAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GovAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *GovAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *GovAttributes) SetLabel(v string) {
	o.Label = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GovAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GovAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GovAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GovAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GovAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GovAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o GovAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GovAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["city_id"] = o.CityId
	toSerialize["role"] = o.Role
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *GovAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"city_id",
		"role",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGovAttributes := _GovAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGovAttributes)

	if err != nil {
		return err
	}

	*o = GovAttributes(varGovAttributes)

	return err
}

type NullableGovAttributes struct {
	value *GovAttributes
	isSet bool
}

func (v NullableGovAttributes) Get() *GovAttributes {
	return v.value
}

func (v *NullableGovAttributes) Set(val *GovAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableGovAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableGovAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGovAttributes(val *GovAttributes) *NullableGovAttributes {
	return &NullableGovAttributes{value: val, isSet: true}
}

func (v NullableGovAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGovAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


