/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOwnCityAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnCityAdmin{}

// UpdateOwnCityAdmin struct for UpdateOwnCityAdmin
type UpdateOwnCityAdmin struct {
	Data UpdateOwnCityAdminData `json:"data"`
}

type _UpdateOwnCityAdmin UpdateOwnCityAdmin

// NewUpdateOwnCityAdmin instantiates a new UpdateOwnCityAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnCityAdmin(data UpdateOwnCityAdminData) *UpdateOwnCityAdmin {
	this := UpdateOwnCityAdmin{}
	this.Data = data
	return &this
}

// NewUpdateOwnCityAdminWithDefaults instantiates a new UpdateOwnCityAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnCityAdminWithDefaults() *UpdateOwnCityAdmin {
	this := UpdateOwnCityAdmin{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateOwnCityAdmin) GetData() UpdateOwnCityAdminData {
	if o == nil {
		var ret UpdateOwnCityAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnCityAdmin) GetDataOk() (*UpdateOwnCityAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateOwnCityAdmin) SetData(v UpdateOwnCityAdminData) {
	o.Data = v
}

func (o UpdateOwnCityAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnCityAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateOwnCityAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOwnCityAdmin := _UpdateOwnCityAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOwnCityAdmin)

	if err != nil {
		return err
	}

	*o = UpdateOwnCityAdmin(varUpdateOwnCityAdmin)

	return err
}

type NullableUpdateOwnCityAdmin struct {
	value *UpdateOwnCityAdmin
	isSet bool
}

func (v NullableUpdateOwnCityAdmin) Get() *UpdateOwnCityAdmin {
	return v.value
}

func (v *NullableUpdateOwnCityAdmin) Set(val *UpdateOwnCityAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnCityAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnCityAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnCityAdmin(val *UpdateOwnCityAdmin) *NullableUpdateOwnCityAdmin {
	return &NullableUpdateOwnCityAdmin{value: val, isSet: true}
}

func (v NullableUpdateOwnCityAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnCityAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


