/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GovData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GovData{}

// GovData struct for GovData
type GovData struct {
	// gov id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes GovAttributes `json:"attributes"`
}

type _GovData GovData

// NewGovData instantiates a new GovData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGovData(id string, type_ string, attributes GovAttributes) *GovData {
	this := GovData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewGovDataWithDefaults instantiates a new GovData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGovDataWithDefaults() *GovData {
	this := GovData{}
	return &this
}

// GetId returns the Id field value
func (o *GovData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GovData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GovData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *GovData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GovData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GovData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *GovData) GetAttributes() GovAttributes {
	if o == nil {
		var ret GovAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GovData) GetAttributesOk() (*GovAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GovData) SetAttributes(v GovAttributes) {
	o.Attributes = v
}

func (o GovData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GovData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *GovData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGovData := _GovData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGovData)

	if err != nil {
		return err
	}

	*o = GovData(varGovData)

	return err
}

type NullableGovData struct {
	value *GovData
	isSet bool
}

func (v NullableGovData) Get() *GovData {
	return v.value
}

func (v *NullableGovData) Set(val *GovData) {
	v.value = val
	v.isSet = true
}

func (v NullableGovData) IsSet() bool {
	return v.isSet
}

func (v *NullableGovData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGovData(val *GovData) *NullableGovData {
	return &NullableGovData{value: val, isSet: true}
}

func (v NullableGovData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGovData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


