/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOwnAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnAdmin{}

// UpdateOwnAdmin struct for UpdateOwnAdmin
type UpdateOwnAdmin struct {
	Data UpdateOwnAdminData `json:"data"`
}

type _UpdateOwnAdmin UpdateOwnAdmin

// NewUpdateOwnAdmin instantiates a new UpdateOwnAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnAdmin(data UpdateOwnAdminData) *UpdateOwnAdmin {
	this := UpdateOwnAdmin{}
	this.Data = data
	return &this
}

// NewUpdateOwnAdminWithDefaults instantiates a new UpdateOwnAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnAdminWithDefaults() *UpdateOwnAdmin {
	this := UpdateOwnAdmin{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateOwnAdmin) GetData() UpdateOwnAdminData {
	if o == nil {
		var ret UpdateOwnAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnAdmin) GetDataOk() (*UpdateOwnAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateOwnAdmin) SetData(v UpdateOwnAdminData) {
	o.Data = v
}

func (o UpdateOwnAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateOwnAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOwnAdmin := _UpdateOwnAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOwnAdmin)

	if err != nil {
		return err
	}

	*o = UpdateOwnAdmin(varUpdateOwnAdmin)

	return err
}

type NullableUpdateOwnAdmin struct {
	value *UpdateOwnAdmin
	isSet bool
}

func (v NullableUpdateOwnAdmin) Get() *UpdateOwnAdmin {
	return v.value
}

func (v *NullableUpdateOwnAdmin) Set(val *UpdateOwnAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnAdmin(val *UpdateOwnAdmin) *NullableUpdateOwnAdmin {
	return &NullableUpdateOwnAdmin{value: val, isSet: true}
}

func (v NullableUpdateOwnAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


