/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateGovData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGovData{}

// UpdateGovData struct for UpdateGovData
type UpdateGovData struct {
	// government id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes UpdateGovDataAttributes `json:"attributes"`
}

type _UpdateGovData UpdateGovData

// NewUpdateGovData instantiates a new UpdateGovData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGovData(id string, type_ string, attributes UpdateGovDataAttributes) *UpdateGovData {
	this := UpdateGovData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateGovDataWithDefaults instantiates a new UpdateGovData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGovDataWithDefaults() *UpdateGovData {
	this := UpdateGovData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateGovData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateGovData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateGovData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateGovData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateGovData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateGovData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateGovData) GetAttributes() UpdateGovDataAttributes {
	if o == nil {
		var ret UpdateGovDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateGovData) GetAttributesOk() (*UpdateGovDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateGovData) SetAttributes(v UpdateGovDataAttributes) {
	o.Attributes = v
}

func (o UpdateGovData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGovData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateGovData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGovData := _UpdateGovData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGovData)

	if err != nil {
		return err
	}

	*o = UpdateGovData(varUpdateGovData)

	return err
}

type NullableUpdateGovData struct {
	value *UpdateGovData
	isSet bool
}

func (v NullableUpdateGovData) Get() *UpdateGovData {
	return v.value
}

func (v *NullableUpdateGovData) Set(val *UpdateGovData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGovData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGovData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGovData(val *UpdateGovData) *NullableUpdateGovData {
	return &NullableUpdateGovData{value: val, isSet: true}
}

func (v NullableUpdateGovData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGovData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


