/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CityAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CityAdmin{}

// CityAdmin struct for CityAdmin
type CityAdmin struct {
	Data CityAdminData `json:"data"`
}

type _CityAdmin CityAdmin

// NewCityAdmin instantiates a new CityAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCityAdmin(data CityAdminData) *CityAdmin {
	this := CityAdmin{}
	this.Data = data
	return &this
}

// NewCityAdminWithDefaults instantiates a new CityAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCityAdminWithDefaults() *CityAdmin {
	this := CityAdmin{}
	return &this
}

// GetData returns the Data field value
func (o *CityAdmin) GetData() CityAdminData {
	if o == nil {
		var ret CityAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CityAdmin) GetDataOk() (*CityAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CityAdmin) SetData(v CityAdminData) {
	o.Data = v
}

func (o CityAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CityAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CityAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCityAdmin := _CityAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCityAdmin)

	if err != nil {
		return err
	}

	*o = CityAdmin(varCityAdmin)

	return err
}

type NullableCityAdmin struct {
	value *CityAdmin
	isSet bool
}

func (v NullableCityAdmin) Get() *CityAdmin {
	return v.value
}

func (v *NullableCityAdmin) Set(val *CityAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableCityAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableCityAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCityAdmin(val *CityAdmin) *NullableCityAdmin {
	return &NullableCityAdmin{value: val, isSet: true}
}

func (v NullableCityAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCityAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


