/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCityStatusData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCityStatusData{}

// UpdateCityStatusData struct for UpdateCityStatusData
type UpdateCityStatusData struct {
	// city id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes UpdateCityStatusDataAttributes `json:"attributes"`
}

type _UpdateCityStatusData UpdateCityStatusData

// NewUpdateCityStatusData instantiates a new UpdateCityStatusData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCityStatusData(id string, type_ string, attributes UpdateCityStatusDataAttributes) *UpdateCityStatusData {
	this := UpdateCityStatusData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateCityStatusDataWithDefaults instantiates a new UpdateCityStatusData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCityStatusDataWithDefaults() *UpdateCityStatusData {
	this := UpdateCityStatusData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateCityStatusData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateCityStatusData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateCityStatusData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateCityStatusData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateCityStatusData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateCityStatusData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateCityStatusData) GetAttributes() UpdateCityStatusDataAttributes {
	if o == nil {
		var ret UpdateCityStatusDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateCityStatusData) GetAttributesOk() (*UpdateCityStatusDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateCityStatusData) SetAttributes(v UpdateCityStatusDataAttributes) {
	o.Attributes = v
}

func (o UpdateCityStatusData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCityStatusData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateCityStatusData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCityStatusData := _UpdateCityStatusData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCityStatusData)

	if err != nil {
		return err
	}

	*o = UpdateCityStatusData(varUpdateCityStatusData)

	return err
}

type NullableUpdateCityStatusData struct {
	value *UpdateCityStatusData
	isSet bool
}

func (v NullableUpdateCityStatusData) Get() *UpdateCityStatusData {
	return v.value
}

func (v *NullableUpdateCityStatusData) Set(val *UpdateCityStatusData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCityStatusData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCityStatusData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCityStatusData(val *UpdateCityStatusData) *NullableUpdateCityStatusData {
	return &NullableUpdateCityStatusData{value: val, isSet: true}
}

func (v NullableUpdateCityStatusData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCityStatusData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


