/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateGov type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGov{}

// UpdateGov struct for UpdateGov
type UpdateGov struct {
	Data UpdateGovData `json:"data"`
}

type _UpdateGov UpdateGov

// NewUpdateGov instantiates a new UpdateGov object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGov(data UpdateGovData) *UpdateGov {
	this := UpdateGov{}
	this.Data = data
	return &this
}

// NewUpdateGovWithDefaults instantiates a new UpdateGov object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGovWithDefaults() *UpdateGov {
	this := UpdateGov{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateGov) GetData() UpdateGovData {
	if o == nil {
		var ret UpdateGovData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateGov) GetDataOk() (*UpdateGovData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateGov) SetData(v UpdateGovData) {
	o.Data = v
}

func (o UpdateGov) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGov) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateGov) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGov := _UpdateGov{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGov)

	if err != nil {
		return err
	}

	*o = UpdateGov(varUpdateGov)

	return err
}

type NullableUpdateGov struct {
	value *UpdateGov
	isSet bool
}

func (v NullableUpdateGov) Get() *UpdateGov {
	return v.value
}

func (v *NullableUpdateGov) Set(val *UpdateGov) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGov) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGov) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGov(val *UpdateGov) *NullableUpdateGov {
	return &NullableUpdateGov{value: val, isSet: true}
}

func (v NullableUpdateGov) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGov) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


