/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateOwnAdminDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnAdminDataAttributes{}

// UpdateOwnAdminDataAttributes struct for UpdateOwnAdminDataAttributes
type UpdateOwnAdminDataAttributes struct {
	// optional label for the user in this city
	Label *string `json:"label,omitempty"`
	// optional position for the user in this city
	Position *string `json:"position,omitempty"`
}

// NewUpdateOwnAdminDataAttributes instantiates a new UpdateOwnAdminDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnAdminDataAttributes() *UpdateOwnAdminDataAttributes {
	this := UpdateOwnAdminDataAttributes{}
	return &this
}

// NewUpdateOwnAdminDataAttributesWithDefaults instantiates a new UpdateOwnAdminDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnAdminDataAttributesWithDefaults() *UpdateOwnAdminDataAttributes {
	this := UpdateOwnAdminDataAttributes{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UpdateOwnAdminDataAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOwnAdminDataAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateOwnAdminDataAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UpdateOwnAdminDataAttributes) SetLabel(v string) {
	o.Label = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *UpdateOwnAdminDataAttributes) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOwnAdminDataAttributes) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *UpdateOwnAdminDataAttributes) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *UpdateOwnAdminDataAttributes) SetPosition(v string) {
	o.Position = &v
}

func (o UpdateOwnAdminDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnAdminDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableUpdateOwnAdminDataAttributes struct {
	value *UpdateOwnAdminDataAttributes
	isSet bool
}

func (v NullableUpdateOwnAdminDataAttributes) Get() *UpdateOwnAdminDataAttributes {
	return v.value
}

func (v *NullableUpdateOwnAdminDataAttributes) Set(val *UpdateOwnAdminDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnAdminDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnAdminDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnAdminDataAttributes(val *UpdateOwnAdminDataAttributes) *NullableUpdateOwnAdminDataAttributes {
	return &NullableUpdateOwnAdminDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateOwnAdminDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnAdminDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


