/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateOwnCityAdminDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnCityAdminDataAttributes{}

// UpdateOwnCityAdminDataAttributes struct for UpdateOwnCityAdminDataAttributes
type UpdateOwnCityAdminDataAttributes struct {
	// optional label for the user in this city
	Label *string `json:"label,omitempty"`
	// optional position for the user in this city
	Position *string `json:"position,omitempty"`
}

// NewUpdateOwnCityAdminDataAttributes instantiates a new UpdateOwnCityAdminDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnCityAdminDataAttributes() *UpdateOwnCityAdminDataAttributes {
	this := UpdateOwnCityAdminDataAttributes{}
	return &this
}

// NewUpdateOwnCityAdminDataAttributesWithDefaults instantiates a new UpdateOwnCityAdminDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnCityAdminDataAttributesWithDefaults() *UpdateOwnCityAdminDataAttributes {
	this := UpdateOwnCityAdminDataAttributes{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UpdateOwnCityAdminDataAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOwnCityAdminDataAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateOwnCityAdminDataAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UpdateOwnCityAdminDataAttributes) SetLabel(v string) {
	o.Label = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *UpdateOwnCityAdminDataAttributes) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOwnCityAdminDataAttributes) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *UpdateOwnCityAdminDataAttributes) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *UpdateOwnCityAdminDataAttributes) SetPosition(v string) {
	o.Position = &v
}

func (o UpdateOwnCityAdminDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnCityAdminDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableUpdateOwnCityAdminDataAttributes struct {
	value *UpdateOwnCityAdminDataAttributes
	isSet bool
}

func (v NullableUpdateOwnCityAdminDataAttributes) Get() *UpdateOwnCityAdminDataAttributes {
	return v.value
}

func (v *NullableUpdateOwnCityAdminDataAttributes) Set(val *UpdateOwnCityAdminDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnCityAdminDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnCityAdminDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnCityAdminDataAttributes(val *UpdateOwnCityAdminDataAttributes) *NullableUpdateOwnCityAdminDataAttributes {
	return &NullableUpdateOwnCityAdminDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateOwnCityAdminDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnCityAdminDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


