openapi: 3.1.0
info:
  title: cities-svc API
  description: API documentation for cities-svc
  version: 0.1.0
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreateCountry:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - create_country
            attributes:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: city name
    UpdateCountry:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: country id
            type:
              type: string
              enum:
                - update_country
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: city name
    UpdateCountryStatus:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: country id
            type:
              type: string
              enum:
                - update_country_status
            attributes:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  description: new country status
    CreateCity:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - create_city
            attributes:
              type: object
              required:
                - country_id
                - name
                - point
                - timezone
              properties:
                country_id:
                  type: string
                  format: uuid
                  description: country id
                name:
                  type: string
                  description: city name
                point:
                  $ref: '#/components/schemas/Point'
                timezone:
                  type: string
                  description: city timezone
                  example: Europe/Berlin
    UpdateCity:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: city id
            type:
              type: string
              enum:
                - update_city
            attributes:
              type: object
              properties:
                point:
                  $ref: '#/components/schemas/Point'
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                  description: city status
                name:
                  type: string
                  description: city name
                icon:
                  type: string
                  format: uri
                  description: city icon uri
                slug:
                  type: string
                  description: city slug
                timezone:
                  type: string
                  description: city timezone
    UpdateCityStatus:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: city id
            type:
              type: string
              enum:
                - update_city
            attributes:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  description: new city status
    UpdateOwnActiveGov:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: user id
            type:
              type: string
              enum:
                - update_own_gov
            attributes:
              type: object
              properties:
                label:
                  type: string
                  description: optional label for the user in this city
    CreateMayor:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - create_mayor
            attributes:
              type: object
              required:
                - city_id
                - user_id
                - label
              properties:
                city_id:
                  type: string
                  format: uuid
                  description: city id
                user_id:
                  type: string
                  format: uuid
                  description: user id
                label:
                  type: string
                  description: label for the user in this city
                  example: City Department of Transportation
    AnswerToInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: invite id
            type:
              type: string
              enum:
                - answer_to_invite
            attributes:
              type: object
              required:
                - answer
              properties:
                answer:
                  type: string
                  description: answer to the invite
                  enum:
                    - accepted
                    - declined
    SentInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: invite id
            type:
              type: string
              enum:
                - sent_invite
            attributes:
              type: object
              required:
                - city_id
                - role
              properties:
                city_id:
                  type: string
                  format: uuid
                  description: ID of the city the invite is for
                role:
                  type: string
                  description: Role assigned to the invited user
    TransferMayor:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: invite id
            type:
              type: string
              enum:
                - transfer_mayor
            attributes:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: ID of the user to be assigned as the new mayor
    CreateInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - create_gov
            attributes:
              type: object
              required:
                - user_id
                - role
                - label
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: user id
                role:
                  type: string
                  description: role of the user in this city
                  example: admin
                label:
                  type: string
                  description: label for the user in this city
                  example: City Department of Transportation
    Country:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/CountryData'
    CountryData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: country id
        type:
          type: string
          enum:
            - country
        attributes:
          $ref: '#/components/schemas/CountryAttributes'
    CountryAttributes:
      type: object
      required:
        - name
        - status
        - created_at
        - updated_at
      properties:
        name:
          type: string
          description: country name
        status:
          type: string
          enum:
            - active
            - inactive
          description: country status
        created_at:
          type: string
          format: date-time
          description: creation date
        updated_at:
          type: string
          format: date-time
          description: last update date
    CountriesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CountryData'
        links:
          $ref: '#/components/schemas/PaginationData'
    City:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/CityData'
    CityData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: city id
        type:
          type: string
          enum:
            - city
        attributes:
          $ref: '#/components/schemas/CityAttributes'
    CityAttributes:
      type: object
      required:
        - country_id
        - point
        - status
        - name
        - timezone
        - created_at
        - updated_at
      properties:
        country_id:
          type: string
          format: uuid
          description: country id
        point:
          $ref: '#/components/schemas/Point'
        status:
          type: string
          enum:
            - active
            - inactive
          description: city status
        name:
          type: string
          description: city name
        icon:
          type: string
          format: uri
          description: city icon uri
        slug:
          type: string
          description: city slug
        timezone:
          type: string
          description: city timezone
        created_at:
          type: string
          format: date-time
          description: creation date
        updated_at:
          type: string
          format: date-time
          description: last update date
    CitiesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CityData'
        links:
          $ref: '#/components/schemas/PaginationData'
    Gov:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/GovData'
    GovData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: gov id
        type:
          type: string
          enum:
            - gov
        attributes:
          $ref: '#/components/schemas/GovAttributes'
    GovAttributes:
      type: object
      required:
        - city_id
        - role
        - label
        - created_at
        - updated_at
      properties:
        city_id:
          type: string
          format: uuid
          description: city id
        role:
          type: string
          description: role of the user in this city
        label:
          type: string
          description: optional label for the user in this city
        created_at:
          type: string
          format: date-time
          description: record creation date
        updated_at:
          type: string
          format: date-time
          description: last update date
    GovsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/GovData'
        links:
          $ref: '#/components/schemas/PaginationData'
    Invite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: invite id
            type:
              type: string
              enum:
                - invite
            attributes:
              type: object
              required:
                - status
                - role
                - city_id
                - token
                - expires_at
                - created_at
              properties:
                status:
                  type: string
                  description: status of the invite
                role:
                  type: string
                  description: role of the user in this city
                city_id:
                  type: string
                  format: uuid
                  description: city id
                token:
                  type: string
                  description: unique token for the invite
                expires_at:
                  type: string
                  format: date-time
                  description: timestamp when the invite will expire
                created_at:
                  type: string
                  format: date-time
                  description: timestamp when the invite was created
    Errors:
      description: 'Standard JSON:API error'
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          description: Non empty array of errors occurred during request processing
          items:
            type: object
            required:
              - title
              - status
            properties:
              title:
                type: string
                description: 'Title is a short, human-readable summary of the problem'
                example: Bad Request
              detail:
                type: string
                description: Detail is a human-readable explanation specific to this occurrence of the problem
                example: Request body was expected
              status:
                type: integer
                description: Status is the HTTP status code applicable to this problem
                example: 400
                enum:
                  - 400
                  - 401
                  - 403
                  - 404
                  - 409
                  - 500
    PaginationData:
      type: object
      required:
        - page_number
        - page_size
        - total_items
      properties:
        page_number:
          type: integer
          format: int64
          description: The current page number.
          example: 1
        page_size:
          type: integer
          format: int64
          description: The number of items per page.
          example: 10
        total_items:
          type: integer
          format: int64
          description: The total number of items available.
          example: 100
    Point:
      type: object
      description: city location
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          format: double
          description: latitude
        longitude:
          type: number
          format: double
          description: longitude
