openapi: 3.1.0
info:
  title: cities-svc API
  description: API documentation for cities-svc
  version: 0.1.0

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    CreateCity:
      $ref: './spec/components/schemas/CreateCity.yaml'
    UpdateCity:
      $ref: './spec/components/schemas/UpdateCity.yaml'
    UpdateCityStatus:
      $ref: './spec/components/schemas/UpdateCityStatus.yaml'
    UpdateOwnAdmin:
      $ref: './spec/components/schemas/UpdateOwnAdmin.yaml'

    SentInvite:
      $ref: './spec/components/schemas/SentInvite.yaml'
    AcceptInvite:
      $ref: './spec/components/schemas/AcceptInvite.yaml'

    City:
      $ref: './spec/components/schemas/City.yaml'
    CityData:
      $ref: './spec/components/schemas/CityData.yaml'
    CityAttributes:
      $ref: './spec/components/schemas/CityAttributes.yaml'
    CitiesCollection:
      $ref: './spec/components/schemas/CitiesCollection.yaml'

    CityAdmin:
      $ref: './spec/components/schemas/CityAdmin.yaml'
    CityAdminData:
      $ref: './spec/components/schemas/CityAdminData.yaml'
    CityAdminAttributes:
      $ref: './spec/components/schemas/CityAdminAttributes.yaml'
    CityAdminsCollection:
      $ref: './spec/components/schemas/CityAdminsCollection.yaml'

    Invite:
      $ref: './spec/components/schemas/Invite.yaml'

    Errors:
      $ref: './spec/components/schemas/Errors.yaml'
    PaginationData:
      $ref: './spec/components/schemas/PaginationData.yaml'
    Point:
      $ref: './spec/components/schemas/Point.yaml'